server:
  port: ${EURIKA_SERVER_PORT:5050}
  max-http-header-size: 10000000

spring:
  application:
    name: ${REGISTRY_NAME:eurika-registry}
  profiles:
    active: ${ENV_PROFILE:dev}

eureka:
  instance:
    hostname: ${EURIKA_SERVER_HOST:localhost}
    preferIpAddress: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka

logging:
  file:
    name: eurika-service.log
    max-history: 10
    max-size: 10MB
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    org.springframework: ${LOG_LEVEL_SPRING:DEBUG}
    root: INFO

management:
  security:
    enabled: ${SPRING_SECURITY_ENABLED:true}