server:
  port: ${GATEWAY_PORT:6060}

spring:
  application:
    name: gateway-server

gateway:
  servers:
    store:
      url: ${STORE_POINT_SERVICE_URL:localhost}
      port: ${STORE_POINT_SERVICE_PORT:4041}
      name: ${STORE_POINT_SERVICE_NAME:store-service}
      desc: ${STORE_POINT_SERVICE_DESC:empty}
    product:
      url: ${PRODUCT_SERVICE_URL:localhost}
      port: ${PRODUCT_SERVICE_PORT:4042}
      name: ${PRODUCT_SERVICE_NAME:product-service}
      desc: ${PRODUCT_SERVICE_DESC:empty}

eureka:
  instance:
    prefer-ip-address: true
    appname: gateway-server
    lease-renewal-interval-in-seconds: ${RENEWAL_INTERVAL:20}
    lease-expiration-duration-in-seconds: ${LEASE_EXPIRATION:40}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
        defaultZone: http://${EURIKA_SERVER_HOST:localhost}:${EURIKA_SERVER_PORT:5050}/eureka

logging:
  level:
    ROOT: ${STORE_POINT_ROOT_LOG_LEVEL:INFO}