server:
  port: ${GATEWAY_PORT:6060}

spring:
  application:
    name: gateway-server

eureka:
  instance:
    prefer-ip-address: true
    appname: gateway-server
    lease-renewal-interval-in-seconds: ${RENEWAL_INTERVAL:20}
    lease-expiration-duration-in-seconds: ${LEASE_EXPIRATION:40}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
        defaultZone: http://${EURIKA_SERVER_HOST:localhost}:${EURIKA_SERVER_PORT:5050}/eureka

