server:
  port: ${CONFIG_SERVER_PORT:7070}

# Server/Rabbit
spring:
  application:
    name: integration-config-server
  rabbitmq:
    host: ${RABBITMQ_HOST:localhostl}
    port: ${RABBITMQ_USER_PORT:5672}
    username: ${RABBITMQ_STANDARD_USERNAME:guest}
    password: ${RABBITMQ_STANDARD_PASSWORD:guest}
  cloud:
    config:
      label: local-config
      server:
        git:
          uri: ${CLOUD_CONFIG_SERVER:https://github.com/Sergeydayneko/config-server}
          username: ${CLOUD_CONFIG_SERVER_LOGIN}
          password: ${CLOUD_CONFIG_SERVER_PASSWORD}
          clone-on-start: true
          skipSslValidation: true
          searchPaths: develop

# Eureka config
eureka:
  instance:
    prefer-ip-address: true
    appname: config-server
    lease-renewal-interval-in-seconds: ${RENEWAL_INTERVAL:20}
    lease-expiration-duration-in-seconds: ${LEASE_EXPIRATION:40}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EURIKA_SERVER_HOST:localhost}:${EURIKA_SERVER_PORT:5050}/eureka

# Cloud bus
management:
  endpoints:
    web:
      exposure:
        include: refresh
  security:
      enabled: ${SPRING_SECURITY_ENABLED:false}
