server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
#        health:
        git:
          uri: ${CLOUD_CONFIG_SERVER:https://github.com/Sergeydayneko/config-server}
          username: ${CLOUD_CONFIG_SERVER_LOGIN:sergeydayneko@mail.ru}
          password: ${CLOUD_CONFIG_SERVER_PASSWORD:E9m7kj16}
          clone-on-start: true
          skipSslValidation: true
