server:
  port: ${CONFIG_SERVER_PORT:7070}

spring:
  application:
    name: integration-config-server
  cloud:
    config:
      server:
        git:
          uri: ${CLOUD_CONFIG_SERVER:https://github.com/Sergeydayneko/config-server}
          username: ${CLOUD_CONFIG_SERVER_LOGIN}
          password: ${CLOUD_CONFIG_SERVER_PASSWORD}
          clone-on-start: true
          skipSslValidation: true
