server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
#        health:
        git:
          uri: ${CLOUD_CONFIG_SERVER:https://github.com/Sergeydayneko/config-server}
          username: ${CLOUD_CONFIG_SERVER_LOGIN}
          password: ${CLOUD_CONFIG_SERVER_PASSWORD}
          clone-on-start: true
          skipSslValidation: true
